services:
  mysql:
    image: mysql:8.4
    container_name: wow_progress_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wow_progress
      MYSQL_USER: wow_user
      MYSQL_PASSWORD: wow_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: wow_progress_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
